[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools", "wheel"]

[project]
name = "NeuralTSNE"
version = "0.1.0"
description = "Implementation of t-SNE in PyTorch with CUDA support and neural network-based initialization"
license = { file = "LICENSE.txt" }
maintainers = [
    { name = "Patryk Tajs", email = "minosyx@gmail.com"}]