name: Check event type

on:
  push:
    branches: ["main"]
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+(.dev[0-9]+)?"

jobs:
  run_on_tag:
    permissions:
      contents: read
      pull-requests: write
      pages: write
      id-token: write

    if: github.ref_type == 'tag'
    uses: ./.github/workflows/package-test.yml
    with:
      version: ${{ github.ref }}
      release: true

  run_on_push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      pages: write
      id-token: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-tags: true
      - name: Check if commit tag exists
        id: check_tag
        continue-on-error: true
        run: echo "TAG_VERSION=$(git describe --candidates=0)" >> $GITHUB_OUTPUT
      - name: Run test on push
        if: steps.check_tag.outputs.TAG_VERSION == ''
        uses: ./.github/workflows/package-test.yml
        with:
          version: 0.0.1
          release: false
