name: Check event type

on:
  push:
    branches: ["main"]
    tags:
      - "v*"

jobs:
  check_on_tag:
    runs-on: ubuntu-latest

    if: github.ref_type == 'tag'
    steps:
      - name: Check if tag in correct format
        run: |
          if [[ ! ${{ github.ref_name }} =~ ^v[0-9]+\.[0-9]+\.[0-9]+(\.dev[0-9]+)?$ ]]; then
            echo "Tag version is not in the correct format. It should be vX.X.X[.devX]"
            exit 1
          fi

  run_on_tag:
    needs: check_on_tag
    if: success()
    permissions:
      contents: read
      pull-requests: write
      pages: write
      id-token: write

    uses: ./.github/workflows/package-test.yml
    with:
      version: ${{ github.ref_name }}
      release: true

  check_on_push:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.check_tag.outputs.TAG_VERSION }}
      exists: ${{ steps.check_tag.outputs.TAG_VERSION != '0.0.1' }}

    if: github.ref_type == 'branch'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-tags: true
      - name: Check if commit tag exists
        id: check_tag
        continue-on-error: true
        run: |
          TAG_VERSION=$(git describe --candidates=0 2>/dev/null || echo "0.0.1")
          echo "TAG_VERSION=$TAG_VERSION" >> $GITHUB_OUTPUT

  run_on_push:
    needs: check_on_push
    if: success() && ${{ needs.check_on_push.outputs.exists != true }}
    permissions:
      contents: read
      pull-requests: write
      pages: write
      id-token: write

    uses: ./.github/workflows/package-test.yml
    with:
      version: ${{ needs.check_on_push.outputs.version }}
      release: false
