name: Release

on:
  workflow_call:
    inputs:
      TAG_VERSION:
        required: true
        type: string
        description: "The version to release"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      COVERAGE_DIR: _site
      MAIN_DIR: NeuralTSNE
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
      - name: Update version
        run: |
          sed -i "s/{{VERSION}}/${{ inputs.TAG_VERSION }}/g" $MAIN_DIR/NeuralTSNE/__init__.py
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel build
      - name: Build and install package
        run: |
          python -m build $MAIN_DIR/. --sdist --wheel --outdir packaged
      - name: Upload built artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: packaged
          if-no-files-found: error

  publish:
    needs: build
    if: success()
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Download built artifact
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: packaged
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          packages-dir: packaged/
