name: Check event type

on:
  push:
    branches: ["main"]
    tags:
      - "v+([0-9]).+([0-9]).+([0-9])?(.dev+([0-9]))"

jobs:
  run_on_tag:
    permissions:
      contents: read
      pull-requests: write
      pages: write
      id-token: write

    if: github.ref_type == 'tag'
    uses: ./.github/workflows/package-test.yml
    with:
      version: ${{ github.ref }}
      release: true

  check_on_push:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.check_tag.outputs.TAG_VERSION }}
      release: ${{ steps.check_tag.outputs.TAG_VERSION != '0.0.1' }}

    if: github.ref_type == 'branch'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-tags: true
      - name: Check if commit tag exists
        id: check_tag
        continue-on-error: true
        run: |
          TAG_VERSION=$(git describe --candidates=0 2>/dev/null || echo "0.0.1")
          echo "TAG_VERSION=$TAG_VERSION" >> $GITHUB_OUTPUT
      - name: Check if tag in correct format
        if: ${{ steps.check_tag.outputs.TAG_VERSION != '0.0.1' }}
        run: |
          if [[ ! ${{ steps.check_tag.outputs.TAG_VERSION }} =~ ^v[0-9]+\.[0-9]+\.[0-9]+(\.dev[0-9]+)?$ ]]; then
            echo "Tag version is not in the correct format. It should be vX.X.X[.devX]"
            exit 1
          fi

  run_on_push:
    needs: check_on_push
    permissions:
      contents: read
      pull-requests: write
      pages: write
      id-token: write

    uses: ./.github/workflows/package-test.yml
    with:
      version: ${{ needs.check_on_push.outputs.version }}
      release: ${{ needs.check_on_push.outputs.release == 'true' }}
